version: '3'
services:
  nginx:
    image: "registry.cn-zhangjiakou.aliyuncs.com/shreade/media-web:202302171804"
    ports:
      - "80:80"
      - "443:443"
    privileged: true
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/cert:/etc/nginx/cert
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/log:/var/log/nginx
      - ./nginx/www/js/config.js:/usr/share/nginx/build/config.js
    restart: always
    container_name: nginx
  app:
    image: "registry.cn-zhangjiakou.aliyuncs.com/shreade/media-server:latest"
    ports:
      - "9095:9095"
      - "5000-5200:5000-5200/udp"
    volumes:
      - ./app/logs:/opt/application/logs
      - ./app/config.json:/opt/application/config.json
    container_name: app
    restart: always
    privileged: true
    user: root
    environment:
      - SRV_NAME=wss
