version: '3'
services:
  nginx:
    image: registry.cn-zhangjiakou.aliyuncs.com/shreade/media-web:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/cert:/etc/nginx/cert
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/log/error.log:/var/log/nginx/error.log
      - ./nginx/www/js/config.js:/usr/share/nginx/html/js/config.js
    restart: always
    container_name: nginx
  app:
    image: registry.cn-zhangjiakou.aliyuncs.com/shreade/media-server:latest
    restart: always
    container_name: app
    volumes:
      - ./app/config.json:/opt/application/config.json
    ports:
        - "8081:8081"
        - "40000-40050:40000-40050/udp"
